#!/bin/sh

inp=$1

decimals=$HOME/decimals/bkb

die () { echo $@; exit 1; }

[ -n "$inp" ] || die "usage: <inp> "

[ -d "$decimals" ] || die "Err: no decimals dir "

ls $decimals/ | grep -i $inp

# {
#   for link in $decimals/* ; do
#     [ -L "$link" ] || continue
#     [ -d "$link" ] || continue
#     bl=$(basename $link)
#     echo $bl
#   done
# } | grep -i $inp


