#!/usr/local/bin/bash
# because bash on mac os x not work with read -i

#debug_url='http://tagi.ch'

target_dir=$1
url_arg=$2

## ----- library -------
os=$(uname)
die () { echo $@; exit 1; }
clip () {
  case "$os" in
    Darwin) printf "$1" | pbcopy ;;
    *) die "Err: os $os not impl" ;;
  esac
}
## ---------------------

base32date=$HOME/tools/utils/base32date
[ -f "$base32date" ] || die "Err: the 'util' '$base32date' is not in ~/tools/utils/"

[ -n "$target_dir" ] || die "usage: <target dir>"
mkdir -p "$target_dir"

via_url=
if [ -n "$debug_url" ] ; then
  via_url="$debug_url"
else
  if [ -n "$url_arg" ] ; then
    via_url="$url_arg"
  else
    read -p "Do you have url (for 'via')?: " via_url
  fi
fi

origtitle= txt_temp_file=
[ -n "$via_url" ] && { 
   txt_temp_file=$(mktemp)
   html_temp_file=$(mktemp)
   wget "$via_url" -O "$html_temp_file"
   origtitle="$(perl -n -e '/\<title\>(.+?)\<\/title\>/ && print $1' $html_temp_file)"
   elinks -dump "$html_temp_file" > "$txt_temp_file"
}

read -p "Enter title: " -e -i "$origtitle" title

[ -n "$title" ] || die "Err: no title"

filetitle=$(perl -e '$ARGV[0] =~ s/[^a-zA-Z0-9]+/_/g; $ARGV[0] =~ s/^_+|_+$//g;  print(lc($ARGV[0]))' "$title")

basetag=$(basename "$target_dir")
echo ""
echo "Please enter some space separated tags for title '$title': "
read -e -i "$basetag " spacetags 
tags=$(perl -e '$ARGV[0] =~ s/[^a-zA-Z0-9]+/_/g; $ARGV[0] =~ s/^_+|_+$//g;  print(lc($ARGV[0]))' "$spacetags")

day=$(date +%d) month=$(date +%m) year=$(date +%Y) hour=$(date +%H) minute=$(date +%M)
date32=$(${base32date} ${year}${month}${day}${hour}${minute})

file_path=
if [ -n "$tags" ] ; then
   file_path="$target_dir"/"${filetitle}--${tags}-$date32".txt
else
   file_path="$target_dir"/"${filetitle}--${date32}".txt
fi

[ -f "$file_path" ] || { 
{
  echo '---'
  echo "title: $origtitle"
  echo "via: $via_url"
  echo "date: $day.$month.$year $hour:$minute"
  echo "tags: $spacetags"
  echo "---"
  echo ""
  [ -f "$txt_temp_file" ] && cat "$txt_temp_file"
} > "$file_path"
}


clip "$file_path" 

echo ""
echo "Done! (file path in clipboard)"
echo "txt: $file_path"

