#!/usr/bin/env python3
#
import sys

import datetime

import base32_crockford
#from bases import Bases
#bases = Bases()


date = 0
if len(sys.argv) > 1:
    strdate=sys.argv[1]
else:
    now = datetime.datetime.now()
    strdate = now.strftime("%Y%m%d%H%M")

#print(str(bases.toBase32(int(strdate))).lower())
print(str(base32_crockford.encode(int(strdate))).lower())

