#!/usr/bin/env python
#
import sys

import datetime

from bases import Bases
bases = Bases()


date = 0
if len(sys.argv) > 1:
    strdate=sys.argv[1]
else:
    now = datetime.datetime.now()
    strdate = now.strftime("%Y%m%d%H%M")

print(bases.toBase58(int(strdate)))
