#!/bin/sh

target_default=mp3

dir=$1
target=$2

[ -d "$dir" ] || { echo "usage:<dir>"; exit 1; }
[ -n "$target" ] || target=$target_default


for f in "$dir"/*.mp4 ; do
  [ -f "$f" ] || continue
  bf=$(basename "$f")
  df=$(dirname "$f")

  bfn=${bf%.*}

   if [ -f "$df/$bfn.$target" ] ; then
      rm -f "$f"
    else
      ffmpeg -i "$f" "$df/$bfn.$target"
      rm -f "$f"
    fi
done
